server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geosus
    username: geosus
    password: geosus
    driver-class-name: org.postgresql.Driver

  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb.core: DEBUG
